### ISSUE TITLE
ModelCheckpoint is error ？ or ...?

### ISSUE THREAD

**Issue by yangchangli** [zepingyu0512/srnn#13]
Train on 25 samples, validate on 3 samples
Epoch 1/10
25/25 [==============================] - 4s 156ms/step - loss: 2.3046 - acc: 0.2000 - val_loss: 2.1626 - val_acc: 0.0000e+00

Epoch 00001: val_acc improved from -inf to 0.00000, saving model to F:\SRNN(8,2)_yelp20131.h5
Epoch 2/10
25/25 [==============================] - 0s 17ms/step - loss: 1.8452 - acc: 0.2000 - val_loss: 1.6156 - val_acc: 0.0000e+00

Epoch 00002: val_acc did not improve from 0.00000
Epoch 3/10
25/25 [==============================] - 0s 17ms/step - loss: 1.5321 - acc: 0.3200 - val_loss: 1.2719 - val_acc: 0.6667

Epoch 00003: val_acc improved from 0.00000 to 0.66667, saving model to F:\SRNN(8,2)_yelp20131.h5
Traceback (most recent call last):

  File "<ipython-input-12-f866f3be68e2>", line 1, in <module>
    runfile('C:/Users/ycl/Desktop/SRNN8-2 - -attention.py', wdir='C:/Users/杨长利/Desktop')

  File "E:\anaconda\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ycl/Desktop/SRNN8-2 - -attention.py", line 239, in <module>
    verbose = 1)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\engine\training_arrays.py", line 217, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\callbacks.py", line 446, in on_epoch_end
    self.model.save(filepath, overwrite=True)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\engine\saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\engine\saving.py", line 78, in _serialize_model
    f['keras_version'] = str(keras_version).encode('utf8')

  File "E:\anaconda\envs\tensorflow\lib\site-packages\keras\utils\io_utils.py", line 214, in __setitem__
    'Group with name "{}" exists.'.format(attr))

KeyError: 'Cannot set attribute. Group with name "keras_version" exists.'

**Comment by yangchangli** [comment]
第一次创建这个文件”SRNN(8,2)_yelp20131”，第一次将信息写入”SRNN(8,2)_yelp20131”是完全正确的，第二次将信息写入”SRNN(8,2)_yelp20131”的就会报错
The first time this file is created "SRNN(8,2)_yelp20131", the first message is written "SRNN(8,2)_yelp20131" is completely correct, the second time the information is written to "SRNN(8,2)
