### ISSUE TITLE
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by SlashChven** [zepingyu0512/srnn#2]
hi~, 我尝试运行了你的代码，在

embed2 = TimeDistributed(Encoder1)(input2)

这行代码中出现了TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64的错误，没有什么头绪，请多多指教，谢谢

**Comment by SlashChven** [comment]
哦，多谢多谢，我去试试

**Comment by ruanchaves** [comment]
I tried to run the code on Tensorflow 1.4 and I still got the same problem. Please help if possible.

Full traceback:

Build Model
2018-08-17 04:51:11.995427: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:28:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "SRNN.py", line 126, in <module>
    embed2 = TimeDistributed(Encoder1)(input2)
  File "/home/ruan/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/ruan/.local/lib/python3.5/site-packages/keras/layers/wrappers.py", line 196, in call
    inputs = K.reshape(inputs, (-1,) + input_shape[2:])
  File "/home/ruan/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1772, in reshape
    return tf.reshape(x, shape)
  File "/home/ruan/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/ruan/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/home/ruan/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

**Comment by ruanchaves** [comment]
I went through the same problem. I tried running it on Tensorflow 1.4.0 and Python 2.7 as it was recommended in this answer and now it's working fine.

**Comment by demonSong** [comment]
instead 'MAX_VALUE/64' to 'int(MAX_VALUE/64)', it can work

**Comment by zepingyu0512** [comment]
@SlashChven @ruanchaves , @demonSong has the answer, hope it will help:)
